### ISSUE TITLE
Budget Tracker functionality

### ISSUE THREAD

**Issue by crosenfrisk** [crosenfrisk/on-budget#7]
- [x] The ability to enter deposits offline.

- [x] The ability to enter expenses offline.

- [x] Offline entries should be added to the tracker when the application is brought back online.
